### ISSUE TITLE
Pie chart on hover

### ISSUE THREAD

**Issue by khasinski** [samdoiron/WhoAmI#3]
If you drag your mouse in and out of the pie chart area (going from one slice to another) in Chrome it gets bigger (zooms) many times, eventually being bigger than the rest of the webpage.

**Comment by jskvoll** [comment]
looks like
![image](https://cloud.githubusercontent.com/assets/1451730/3215123/6f2076dc-efbb-11e3-94f5-e90612dcbfdf.png)

**Comment by waldyrious** [comment]
That only happens to me if I move the cursor _really_ fast in and out of the area (so the enlarging animation kicks in before the shrinking animation has a chance to finish).

**Comment by samdoiron** [comment]
Fixed in commit 2460425
